# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  projects: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: '--configuration Release'

steps:
- task: dotNetCoreCLI@1
  inputs:
    command: restore
    projects: '$(projects)'

- task: dotNetCoreCLI@1
  inputs:
    command: build
    projects: '$(projects)'
    arguments: '$(buildConfiguration)'

- task: CmdLine@2
  inputs:
    script: 'dir bin\Release'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'bin\Release\netstandard2.1\publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'